name: projectdesawisata
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Pendaftaran aset gambar Anda (Sudah rapi tanpa duplikat)
  assets:
    - assets/login_bg.jpeg
    - assets/sumber_agung_bg.jpeg
    - assets/Lengkung_Langit_Dua.jpg
    - assets/Kampung_vietnam.jpeg
    - assets/Paraduta_hill.jpeg